### ISSUE TITLE
Undefined access of variable

### ISSUE THREAD

**Issue by TwelveGem** [UA-NASA-Robotics/Roobot-Over-IP#6]
Inside of UnitiyTypes.hpp, Axis::name is attempted to be accessed, but the compiler and I could not find a definition of it. The code in question is:
```
#define DEFINE_ACCESSOR(name)
    T &name() {
        return data[static_cast<std::size_t>(Axis::name)];
    }  // Accessor function for each enum value
    const T &name() const {
        return data[static_cast<std::size_t>(Axis::name)];
    }  // Const accessor function for each enum value
    void name(T value) {
        data[static_cast<std::size_t>(Axis::name)] = value;
    }  // Mutator function for each enum value
...
};
```
The definition of Axis is:
```
enum class Axis { X, Y, Z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P };
```
Here is the error that I am receiving in my compiler
![image](https://github.com/user-attachments/assets/413b7c6c-725f-43da-b2f8-225a8ae5177b)
Is there something I'm missing, or is there something missing in the code

**Comment by Mapy542** [comment]
Removed offending code
